site_name: Cancer Genomics Workshop
site_description: This contains all material for the Cancer Genomics workshop.
site_author: Authors

#site_url: 'https://bpa-csiro-workshops.github.io/cancer-manuals'

copyright: '&copy; The authors; 2017-'

#Documentation and theme
theme: material

# Options
extra:
  palette:
    primary: 'indigo'
    accent: 'light blue'

  feature:
    tabs: false

  site_favicon: 'media/logos/Bioplatforms-Australia-favicon2.png'

markdown_extensions:
    - admonition
    - smarty
    - tables
    - markdown_include.include
    - codehilite(linenums=True)
#    - codehilite
    - toc(permalink=true)
    - mdx_math
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist(custom_checkbox=true)
    - pymdownx.tilde
    - pymdownx.details

extra_css:
    #- css/extra.css
    - css/details.css

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - js/details.js

pages:
- Home: index.md
- The Trainers: trainers/trainers.md
- Timetable: timetables/timetable_cancer.md
- Workshop Information: preamble.md

# - All Modules:
#    - Introduction to Command Line: modules/cancer-module-cli/commandline.md
#    - Cancer QC: modules/cancer-module-qc/ngs-qc.md
#     - Cancer Read Alignment: modules/cancer-module-alignment/alignment.md
#     - Copy Number Variation: modules/cancer-module-cnv/cnv-tut.md
#     - Single Nucleotide Variant Calling and Annotation: modules/cancer-module-snv/snv.md
#     - Somatic Mutations:
#         - Assessing somatic mutational signatures: modules/cancer-module-somatic/01_signatures.md
#         - Cohort analysis for the identification of driver genes: modules/cancer-module-somatic/02_intogen.md
#     - Structural Variant Analysis: modules/cancer-module-sv/sv_tut.md
#     - Cancer Variant Visualisation: modules/cancer-module-viz/visu.md
#     - Bacterial Assembly: modules/denovo-module-bac/bac_asm.md
#     - DeNovo Introduction to Command Line: modules/denovo-module-cli/commandline.md
#     - Eukaryote Assembly: modules/denovo-module-euk/eukaryotic_assem.md
#     - Scaffolding: modules/denovo-module-scaffolding/scaffold.md

- Hands-on Modules:
    - Introduction to Command Line: modules/cancer-module-cli/commandline.md
    - Quality Control: modules/cancer-module-qc/ngs-qc.md
    - Read Alignment: modules/cancer-module-alignment/alignment.md
    - Single Nucleotide Variant Calling and Annotation: modules/cancer-module-snv/snv.md
    - Copy Number Variation: modules/cancer-module-cnv/cnv-tut.md
    - Structural Variant Analysis: modules/cancer-module-sv/sv_tut.md
    - Somatic Mutations:
        - Assessing somatic mutational signatures: modules/cancer-module-somatic/01_signatures.md
        - Cohort analysis for the identification of driver genes: modules/cancer-module-somatic/02_intogen.md
    - Variant Visualisation: modules/cancer-module-viz/visu.md

- License: license.md
